services:
  clinic-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: rayyandev/clinic-bot:latest
    container_name: clinic-bot
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=Asia/Tashkent
    volumes:
      - ./data:/app/data
