services:
  clinic-bot:
    build: .
    image: rayyandev/clinic-bot:latest
    container_name: clinic-bot
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=Asia/Tashkent
    volumes:
      - ./data:/app/data

# Named volume olib tashlandi, endi faqat lokal papka ishlatiladi
